name: Flutter Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Clean Cache
        run: |
          rm -rf ~/.pub-cache
          dart pub cache repair
      - name: Debug Dart Version
        run: |
          dart --version
          which dart

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'
          sdk: 3.7.2
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test test/main_test.dart --reporter expanded
